### ISSUE TITLE
Produce graphical summary of validation checks

### ISSUE THREAD

**Issue by Bisaloo** [covid19-forecast-hub-europe/covid19-forecast-hub-europe#169]
It might be easier for participants if the validation checks produced a nice graphical summary of what passed and what failed instead of having to read through the full GitHub actions log.

The [pointblank R package](https://github.com/rich-iannone/pointblank) seems well-suited for this task. Here's an image from their [README](https://rich-iannone.github.io/pointblank/):

![](https://raw.githubusercontent.com/rich-iannone/pointblank/master/man/figures/agent_report.png)

It means that the validation check would move from python to R. Is this an issue?

**Comment by sbfnk** [comment]
This looks very nice - and people are definitely struggling with the validation checks, especially at first submission. I see two potential issues:

1) Divergence from the US Forecast Hub where the checks are implemented in python (and which we've largely copied: https://github.com/reichlab/covid19-forecast-hub/tree/master/code/validation) - it's been helpful in the past to have this mirrored, e.g. when putting in the faster validation check (only running on the latest forecast submitted (implemented here: https://github.com/epiforecasts/covid19-forecast-hub-europe-validations/
2) At the moment the validation takes ca. 30 seconds thanks to the speed improvement mentioned above. The github actions we have that are based on R all take ca. 10 minutes to initialise because of the need to install R and package dependencies.

**Comment by seabbs** [comment]
That looks very nice. 

For 2. I think R and package install should be able to be cached in GitHub actions and hence be faster. Their is some effort in that direction here: https://github.com/epiforecasts/covidregionaldata/blob/85474dd8deb6a5c33cf52c0378f6365ba523db45/.github/workflows/check-full.yaml#L57

though I imagine there are better solutions. 

Not sure that helps with 1. though.

**Comment by sbfnk** [comment]
Point 1. is not 100% critical (but would obviously require a rewrite of all the checks). Watching the "person-vs-machine" battles unfolding every week as teams confront the Metadata checks makes me think that there's room for improvement - though, that said, usually teams battle this only once upon first submission and are fine for subesquent submissions. So far nobody seems to have given up completely.

**Comment by Bisaloo** [comment]
Regarding point 2, beyond the caching that @seabbs mentioned, a good option would be to install precompiled binaries from [RStudio Package Manager](https://packagemanager.rstudio.com/).

**Comment by sbfnk** [comment]
Closing this as work on validation is progressing elsewhere.
